### ISSUE TITLE
모집 공지, 시작 기간에 banner, header가 바뀌지 않는 문제

### ISSUE THREAD

**Issue by emost22** [Nexters/teamnexters.com#23]
모집 공지, 시작 기간에 바뀐 banner, header가 적용되지 않는 문제가 있습니다.
![image](https://user-images.githubusercontent.com/60142959/233851082-c1b3b3d7-aecf-4463-bfe8-deaae8da7532.png)
스프레드 시트 Beta입니다. 모집 예고일을 오늘인 4/24로 작성하였습니다.
![image](https://user-images.githubusercontent.com/60142959/233851316-a40bdde8-cb40-4f06-93bb-cdfc0d161cdb.png)
![image](https://user-images.githubusercontent.com/60142959/233851305-f5e9a422-39bd-43cc-a230-77e968878273.png)
![image](https://user-images.githubusercontent.com/60142959/233851373-42b180ac-8472-4c83-885e-97963eb07159.png)
`this.notice_day < 0`이 성립되지 않아 모집 공지 당일이 되었음에도 false가 찍히는 모습입니다.
따라서 banner, header는 변경되지 않습니다.

이에 `before_recruitment`, `is_recruiting` 값 계산에 문제가 있음을 파악하였고 이를 수정합니다.

---

추가로 현재 main 및 recruitment 페이지 내 배너는 모집 공지기간에 바뀌고 있으며,
색이 어두운 배너라면 그에맞게 header가 변경되어야 합니다.

현재 `layout/recruitment.vue` 파일 내에는 `s_day`, `d_day`, `is_recruiting` 함수만 존재하여 `notice_day`, `before_recruiting` 함수를 추가할 예정입니다.

**Comment by CODe5753** [comment]
> 값 계산에 문제가 있음을 파악하여 이를 수정

어떤 문제가 있었는지도 기재해주세요~!

**Comment by emost22** [comment]
수정했습니다

**Comment by CODe5753** [comment]
> 현재 layout/recruitment.vue 파일 내에는 s_day, d_day, is_recruiting 함수만 존재하여 notice_day, before_recruiting 함수를 추가할 예정입니다.

추가되는 이유도 궁금합니다

**Comment by emost22** [comment]
배너가 notice 기간부터 변경됨에 따라 header도 white로 변경될 수 있도록 notice_day를 추가하려고 합니다.
