### ISSUE TITLE
후원사 배너 등록

### ISSUE THREAD

**Issue by emost22** [Nexters/teamnexters.com#28]
Nexters 23기에서 SBA SeSAC의 후원을 받을 예정이고, 몇 가지 요구사항을 제시하였습니다.

### 요구 조건
> teamnexters 홈페이지에 해당하는 내용만 작성합니다.
1. 홈페이지에 홍보를 위한 배너를 추가할 것.
   + 클릭 시 [새싹톤 모집](https://sesacthon-apply.goorm.io/) 페이지로 이동합니다.
   + 배너는 메인 페이지를 제외한 `footer`에 추가될 예정입니다.
2. 홈페이지 내 스폰서 목록에 `SBA SeSAC`을 추가할 것.
   + 클릭 시 [SeSAC](https://sesac.seoul.kr/common/greeting.do) 페이지로 이동합니다.
   + 스프레드 시트에 추가만 하면 되고, 코드의 변경은 없습니다.

### 기간
현재 새싹톤의 모집 기간이 `5.9(화) 17:00` 까지입니다.
배너 노출 기간은 모집 마감일인 `5.9`까지 or 기간 연장 시 `5.12`까지 입니다.

### 적용될 이미지
<details>
<summary>PC</summary>
<img src="https://user-images.githubusercontent.com/60142959/236206868-f72326c4-da83-4c23-9767-95ce55a7b378.png" alt="pc"/>
</details>
<details>
<summary>Tablet</summary>
<img src="https://user-images.githubusercontent.com/60142959/236208731-27995885-0663-4759-af65-8f007dd7c9cd.png" alt="tablet"/>
</details>
<details>
<summary>Mobile</summary>
<img src="https://user-images.githubusercontent.com/60142959/236208848-596dac2a-4467-4b8a-ae18-ccb96b9912b6.png" alt="mobile"/>
</details>

단기간만 적용되는 부분이기 때문에 구글드라이브에 이미지를 업로드해서 얻을 수 있는 id 값을 활용하여 이미지를 띄울 계획입니다.

**Comment by CODe5753** [comment]
모바일 배너가 좀 많이 큰 것 같아요
화면에 표시되는 크기때문에 보통 화면의 width가 줄어들면 height도 줄어들어서 사이즈별로 크기가 다른 이미지를 배너등록 하는데, 보여주신 이미지는 모두 동일한 비율의 이미지 같네요(1920x1680에 최적화 된)
모바일의 경우 그림빼고 텍스트만 들어가도 충분한데 이런 요구사항은 협의 불가능할까요?
요건 필수는 아니고 제 개인적인 의견을 드려봤습니다!

**Comment by emost22** [comment]
@CODe5753 
지금 같은 이미지를 쓰고 있지만 pc, tablet, mobile 에 따라 다른 크기의 이미지로 보여주고 있습니다.
그리고 vw를 이용해서 화면 크기에 따라 다른 크기의 이미지가 보여집니다.

작은 크기의 이미지를 다시 요청 드리거나 텍스트로 변경하는 방안은 안될 것 같다는 CEO의 답변을 받았습니다.
그래서 모바일에 표시될 이미지의 크기가 크다면 절반으로 줄여보는 건 어떻게 생각하시나요?

![image](https://user-images.githubusercontent.com/60142959/236386833-dcaa6bc1-b7c3-438d-a310-00ac495e0afd.png)
실제 모바일 화면으로는 이렇게 보여지고 있고,

![image](https://user-images.githubusercontent.com/60142959/236389191-3ea6ce73-aa5f-483c-8a0f-4ad08714ea22.png)
모바일에 표시될 이미지를 절반으로 줄이면 위 사진처럼 보여집니다. 크기는 한 줄에 두 개가 들어갈 정도입니다.

**Comment by emost22** [comment]
https://sesacthon-apply.goorm.io/
지원서 제출 기간이 `~5.14 17:00 `으로 연장되었습니다.
따라서 5.14 이후에 revert 예정입니다.
